/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memory_package;

/**
 *
 * @author Troy
 */
public class Start_memory extends javax.swing.JPanel {

    /**
     * Creates new form Start_memory
     */
    public Start_memory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Start");
        jButton1.setActionCommand("StartBtn");
        add(jButton1);
        jButton1.setBounds(310, 253, 57, 23);

        jButton2.setText("Sluiten");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(46, 253, 65, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Troy\\Documents\\Memory Game\\Afbeeldingen Kaarten\\Kaar achtergronden\\Bikini_Bottom_Background.jpg")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
